import { useState, useEffect } from 'react'
import type { Email, Klant, Project, Offerte, OfferteItem, MontageAfspraak, Taak, Factuur, FactuurItem } from '@/types'
import { safeSetItem } from '@/utils/localStorageUtils'

const storageKeys = [
  'forgedesk_klanten',
  'forgedesk_projecten',
  'forgedesk_taken',
  'forgedesk_offertes',
  'forgedesk_offerte_items',
  'forgedesk_documenten',
  'forgedesk_emails',
  'forgedesk_events',
  'forgedesk_grootboek',
  'forgedesk_btw_codes',
  'forgedesk_kortingen',
  'forgedesk_nieuwsbrieven',
  'forgedesk_app_settings',
  'forgedesk_montage_afspraken',
  'forgedesk_werkbonnen',
  'forgedesk_facturen',
  'forgedesk_factuur_items',
]

// ── Demo seed data (only used when localStorage is empty) ──

function daysAgo(days: number, hours = 9, minutes = 0): string {
  const d = new Date()
  d.setDate(d.getDate() - days)
  d.setHours(hours, minutes, 0, 0)
  return d.toISOString()
}

const demoKlanten: Klant[] = [
  {
    id: 'klant-001',
    user_id: 'demo-user',
    bedrijfsnaam: 'Bakkerij Van Dijk',
    contactpersoon: 'Pieter van Dijk',
    email: 'pieter@bakkerijvandijk.nl',
    telefoon: '06-12345678',
    adres: 'Broodstraat 12',
    postcode: '3011 AB',
    stad: 'Rotterdam',
    land: 'Nederland',
    website: 'www.bakkerijvandijk.nl',
    kvk_nummer: '12345678',
    btw_nummer: 'NL123456789B01',
    status: 'actief',
    tags: ['horeca', 'vaste klant'],
    notities: 'Vaste klant sinds 2020. Graag lichtreclame en raambelettering.',
    contactpersonen: [
      { id: 'cp-001', naam: 'Pieter van Dijk', functie: 'Eigenaar', email: 'pieter@bakkerijvandijk.nl', telefoon: '06-12345678', is_primair: true },
    ],
    created_at: daysAgo(120),
    updated_at: daysAgo(5),
  },
  {
    id: 'klant-002',
    user_id: 'demo-user',
    bedrijfsnaam: 'Garage Jansen',
    contactpersoon: 'Mark Jansen',
    email: 'mark@garagejansen.nl',
    telefoon: '06-98765432',
    adres: 'Industrieweg 44',
    postcode: '2725 AD',
    stad: 'Zoetermeer',
    land: 'Nederland',
    website: 'www.garagejansen.nl',
    kvk_nummer: '87654321',
    btw_nummer: 'NL987654321B01',
    status: 'actief',
    tags: ['automotive', 'groot project'],
    notities: 'Nieuw pand, complete signing nodig.',
    contactpersonen: [
      { id: 'cp-002', naam: 'Mark Jansen', functie: 'Directeur', email: 'mark@garagejansen.nl', telefoon: '06-98765432', is_primair: true },
    ],
    created_at: daysAgo(60),
    updated_at: daysAgo(2),
  },
  {
    id: 'klant-003',
    user_id: 'demo-user',
    bedrijfsnaam: 'Restaurant De Gouden Leeuw',
    contactpersoon: 'Sophie de Groot',
    email: 'sophie@degoudenleeuw.nl',
    telefoon: '06-55544433',
    adres: 'Marktplein 7',
    postcode: '2611 GH',
    stad: 'Delft',
    land: 'Nederland',
    website: 'www.degoudenleeuw.nl',
    kvk_nummer: '55667788',
    btw_nummer: 'NL556677889B01',
    status: 'actief',
    tags: ['horeca', 'terras'],
    notities: 'Terrassigning en menuboards.',
    contactpersonen: [
      { id: 'cp-003', naam: 'Sophie de Groot', functie: 'Manager', email: 'sophie@degoudenleeuw.nl', telefoon: '06-55544433', is_primair: true },
    ],
    created_at: daysAgo(30),
    updated_at: daysAgo(1),
  },
  {
    id: 'klant-004',
    user_id: 'demo-user',
    bedrijfsnaam: 'Advocatenkantoor Visser & Partners',
    contactpersoon: 'Lisa Visser',
    email: 'l.visser@visserpartners.nl',
    telefoon: '06-11223344',
    adres: 'Herengracht 200',
    postcode: '1016 BS',
    stad: 'Amsterdam',
    land: 'Nederland',
    website: 'www.visserpartners.nl',
    kvk_nummer: '33445566',
    btw_nummer: 'NL334455667B01',
    status: 'prospect',
    tags: ['zakelijk', 'premium'],
    notities: 'Interesse in gevelreclame en kantoorsigning.',
    contactpersonen: [
      { id: 'cp-004', naam: 'Lisa Visser', functie: 'Partner', email: 'l.visser@visserpartners.nl', telefoon: '06-11223344', is_primair: true },
    ],
    created_at: daysAgo(10),
    updated_at: daysAgo(1),
  },
  {
    id: 'klant-005',
    user_id: 'demo-user',
    bedrijfsnaam: 'PrintWorks BV',
    contactpersoon: 'Thomas Bakker',
    email: 'thomas@printworks.nl',
    telefoon: '06-77889900',
    adres: 'Grafisch Centrum 15',
    postcode: '3500 AA',
    stad: 'Utrecht',
    land: 'Nederland',
    website: 'www.printworks.nl',
    kvk_nummer: '99887766',
    btw_nummer: 'NL998877665B01',
    status: 'actief',
    tags: ['leverancier', 'print'],
    notities: 'Leverancier voor groot formaat prints en vinyl.',
    contactpersonen: [
      { id: 'cp-005', naam: 'Thomas Bakker', functie: 'Sales Manager', email: 'thomas@printworks.nl', telefoon: '06-77889900', is_primair: true },
    ],
    created_at: daysAgo(90),
    updated_at: daysAgo(3),
  },
]

const demoEmails: Email[] = [
  // ── INBOX ──
  {
    id: 'email-001',
    user_id: 'demo-user',
    gmail_id: 'gm-001',
    van: 'Pieter van Dijk <pieter@bakkerijvandijk.nl>',
    aan: 'studio@signcompany.nl',
    onderwerp: 'Offerte lichtreclame gevel - graag reactie',
    inhoud: `Hoi,\n\nBedankt voor de offerte die jullie vorige week hebben gestuurd voor de lichtreclame op de gevel. Het ziet er goed uit!\n\nIk heb nog een paar vragen:\n- Kunnen de letters ook in warm wit (3000K) LED?\n- Wat is de levertijd als we deze week akkoord geven?\n- Is montage op zaterdag mogelijk?\n\nHoor graag van jullie.\n\nMet vriendelijke groet,\nPieter van Dijk\nBakkerij Van Dijk`,
    datum: daysAgo(0, 10, 30),
    gelezen: false,
    starred: true,
    labels: ['offerte', 'klant'],
    bijlagen: 0,
    map: 'inbox',
    created_at: daysAgo(0, 10, 30),
  },
  {
    id: 'email-002',
    user_id: 'demo-user',
    gmail_id: 'gm-002',
    van: 'Mark Jansen <mark@garagejansen.nl>',
    aan: 'studio@signcompany.nl',
    onderwerp: 'RE: Planning signing nieuw pand',
    inhoud: `Hallo,\n\nSuper dat jullie volgende week langs kunnen komen voor de opname. Dinsdag of woensdag schikt ons het beste, bij voorkeur in de ochtend.\n\nHet pand is al toegankelijk via de zijingang. Ik zal zorgen dat er iemand aanwezig is om jullie rond te leiden.\n\nOok nog even: we willen graag de reclamezuil bij de ingang meenemen in de offerte. Kunnen jullie daar ook naar kijken?\n\nGroet,\nMark Jansen\nGarage Jansen`,
    datum: daysAgo(0, 9, 15),
    gelezen: false,
    starred: false,
    labels: ['project', 'klant'],
    bijlagen: 0,
    map: 'inbox',
    created_at: daysAgo(0, 9, 15),
  },
  {
    id: 'email-003',
    user_id: 'demo-user',
    gmail_id: 'gm-003',
    van: 'Thomas Bakker <thomas@printworks.nl>',
    aan: 'studio@signcompany.nl',
    onderwerp: 'Prijslijst Q1 2026 - vinyl en printmaterialen',
    inhoud: `Beste,\n\nHierbij ontvang je onze nieuwe prijslijst voor Q1 2026. Er zijn een paar wijzigingen:\n\n- 3M IJ180Cv3 gegoten vinyl: +3% (wereldwijde prijsstijging)\n- Avery MPI 1005 Easy Apply: prijs ongewijzigd\n- Laminaat Orafol 290: -5% (actieprijs tot eind maart)\n\nDe prijslijst vind je in de bijlage. Voor groot formaat bestellingen (>100m²) maken we altijd een maatwerkofferte.\n\nVragen? Bel gerust.\n\nMet vriendelijke groet,\nThomas Bakker\nPrintWorks BV`,
    datum: daysAgo(1, 14, 0),
    gelezen: true,
    starred: false,
    labels: ['leverancier'],
    bijlagen: 1,
    map: 'inbox',
    created_at: daysAgo(1, 14, 0),
  },
  {
    id: 'email-004',
    user_id: 'demo-user',
    gmail_id: 'gm-004',
    van: 'Sophie de Groot <sophie@degoudenleeuw.nl>',
    aan: 'studio@signcompany.nl',
    onderwerp: 'Terrassigning en menuboards - interesse',
    inhoud: `Goedemiddag,\n\nVia een collega-ondernemer hoorde ik dat jullie mooie terrassigning maken. Wij zijn op zoek naar:\n\n1. Menuboards voor buiten (weerbestendig, makkelijk te updaten)\n2. Windschermen met ons logo voor het terras\n3. Eventueel een uithandbord\n\nKunnen jullie eens langskomen voor een vrijblijvend adviesgesprek?\n\nMet vriendelijke groet,\nSophie de Groot\nRestaurant De Gouden Leeuw\nMarktplein 7, Delft`,
    datum: daysAgo(2, 11, 45),
    gelezen: true,
    starred: true,
    labels: ['klant', 'offerte'],
    bijlagen: 0,
    map: 'inbox',
    created_at: daysAgo(2, 11, 45),
  },
  {
    id: 'email-005',
    user_id: 'demo-user',
    gmail_id: 'gm-005',
    van: 'Lisa Visser <l.visser@visserpartners.nl>',
    aan: 'studio@signcompany.nl',
    onderwerp: 'Gevelreclame Herengracht - offerte aanvraag',
    inhoud: `Geachte heer/mevrouw,\n\nWij zijn op zoek naar een professioneel bedrijf voor de gevelreclame van ons kantoor aan de Herengracht 200 in Amsterdam.\n\nWij denken aan:\n- RVS letters op de gevel (onverlicht)\n- Naambord bij de voordeur\n- Eventueel signing in de hal\n\nGezien de monumentale status van het pand is vergunning belangrijk. Hebben jullie hier ervaring mee?\n\nGraag ontvang ik een offerte met referenties.\n\nMet vriendelijke groet,\nMr. Lisa Visser\nVisser & Partners Advocaten`,
    datum: daysAgo(3, 16, 20),
    gelezen: true,
    starred: false,
    labels: ['klant', 'offerte'],
    bijlagen: 0,
    map: 'inbox',
    created_at: daysAgo(3, 16, 20),
  },
  {
    id: 'email-006',
    user_id: 'demo-user',
    gmail_id: 'gm-006',
    van: 'Gemeente Rotterdam <vergunningen@rotterdam.nl>',
    aan: 'studio@signcompany.nl',
    onderwerp: 'Vergunning reclameuiting REF-2026-0182 goedgekeurd',
    inhoud: `Geachte aanvrager,\n\nHierbij bevestigen wij dat de aanvraag voor een reclameuiting op het adres Broodstraat 12, 3011 AB Rotterdam is goedgekeurd.\n\nReferentienummer: REF-2026-0182\nType: Lichtreclame (doosletters)\nAfmeting: 3.500 x 600 mm\nVergunning geldig tot: 31-12-2030\n\nDe vergunning is als bijlage bijgevoegd. Neem bij vragen contact op met het loket Bouwvergunningen.\n\nMet vriendelijke groet,\nGemeente Rotterdam\nAfdeling Vergunningen`,
    datum: daysAgo(4, 8, 0),
    gelezen: true,
    starred: true,
    labels: ['project'],
    bijlagen: 1,
    map: 'inbox',
    created_at: daysAgo(4, 8, 0),
  },
  {
    id: 'email-007',
    user_id: 'demo-user',
    gmail_id: 'gm-007',
    van: 'Pieter van Dijk <pieter@bakkerijvandijk.nl>',
    aan: 'studio@signcompany.nl',
    onderwerp: 'Raambelettering ook aanpassen?',
    inhoud: `Hoi,\n\nNog even een extra vraag: naast de lichtreclame willen we ook de raambelettering vernieuwen. We hebben nieuwe openingstijden en willen een fris design.\n\nKunnen jullie dit meenemen in de offerte? Gaat om 2 ramen van elk ca. 1.50 x 2.00 meter.\n\nAlvast bedankt!\n\nPieter`,
    datum: daysAgo(5, 13, 0),
    gelezen: true,
    starred: false,
    labels: ['klant', 'offerte'],
    bijlagen: 0,
    map: 'inbox',
    created_at: daysAgo(5, 13, 0),
  },

  // ── VERZONDEN ──
  {
    id: 'email-010',
    user_id: 'demo-user',
    gmail_id: 'gm-010',
    van: 'Sign Company <studio@signcompany.nl>',
    aan: 'pieter@bakkerijvandijk.nl',
    onderwerp: 'Offerte OFR-2026-018 - Lichtreclame Bakkerij Van Dijk',
    inhoud: `Beste Pieter,\n\nHierbij ontvang je onze offerte voor de lichtreclame op de gevel van Bakkerij Van Dijk.\n\nSamenvatting:\n- Doosletters met LED verlichting (6500K daglicht wit)\n- Materiaal: 3mm aluminium, wit gepoedercoat\n- Afmeting: 3.500 x 600 mm\n- Inclusief montage en aansluiting\n\nTotaal: € 3.850,- excl. BTW\n\nDe offerte is 30 dagen geldig. Bij akkoord is de levertijd ca. 3-4 weken.\n\nMocht je vragen hebben, neem gerust contact op!\n\nMet vriendelijke groet,\nSign Company`,
    datum: daysAgo(6, 15, 30),
    gelezen: true,
    starred: false,
    labels: ['offerte'],
    bijlagen: 1,
    map: 'verzonden',
    created_at: daysAgo(6, 15, 30),
  },
  {
    id: 'email-011',
    user_id: 'demo-user',
    gmail_id: 'gm-011',
    van: 'Sign Company <studio@signcompany.nl>',
    aan: 'mark@garagejansen.nl',
    onderwerp: 'Afspraak opname signing nieuw pand',
    inhoud: `Hallo Mark,\n\nBedankt voor je interesse in onze signing oplossingen voor het nieuwe pand.\n\nIk stel voor om volgende week langs te komen voor een opname. Dan bekijken we samen de mogelijkheden voor:\n- Gevelreclame\n- Zuil bij de ingang\n- Interne signing\n- Eventueel autobelettering\n\nWelke dag en tijd schikt jou het beste?\n\nMet vriendelijke groet,\nSign Company`,
    datum: daysAgo(2, 10, 0),
    gelezen: true,
    starred: false,
    labels: ['project', 'klant'],
    bijlagen: 0,
    map: 'verzonden',
    created_at: daysAgo(2, 10, 0),
  },
  {
    id: 'email-012',
    user_id: 'demo-user',
    gmail_id: 'gm-012',
    van: 'Sign Company <studio@signcompany.nl>',
    aan: 'l.visser@visserpartners.nl',
    onderwerp: 'RE: Gevelreclame Herengracht - vrijblijvend advies',
    inhoud: `Geachte mevrouw Visser,\n\nBedankt voor uw interesse. Wij hebben ruime ervaring met signing op monumentale panden in Amsterdam, waaronder de Keizersgracht en Prinsengracht.\n\nWij adviseren RVS letters in geborsteld of gepolijst afwerking. Dit past uitstekend bij de uitstraling van een advocatenkantoor.\n\nWat betreft de vergunning: wij verzorgen de volledige vergunningsaanvraag bij de gemeente Amsterdam (Welstandscommissie). Dit is bij monumentale panden verplicht.\n\nZal ik een afspraak inplannen om de mogelijkheden te bespreken? Ik kan ook referenties sturen van vergelijkbare projecten.\n\nMet vriendelijke groet,\nSign Company`,
    datum: daysAgo(2, 16, 45),
    gelezen: true,
    starred: false,
    labels: ['klant', 'offerte'],
    bijlagen: 0,
    map: 'verzonden',
    created_at: daysAgo(2, 16, 45),
  },

  // ── CONCEPTEN ──
  {
    id: 'email-020',
    user_id: 'demo-user',
    gmail_id: 'gm-020',
    van: 'Sign Company <studio@signcompany.nl>',
    aan: 'sophie@degoudenleeuw.nl',
    onderwerp: 'Offerte terrassigning De Gouden Leeuw',
    inhoud: `Beste Sophie,\n\nHierbij onze offerte voor de terrassigning:\n\n1. Menuboards buiten (2 stuks) - Dibond met wisselframe\n2. Windschermen (4 stuks) - Full color geprint op mesh\n3. Uithandbord - Dubbelzijdig met LED\n\n[CONCEPT - prijzen nog invullen]\n\nMet vriendelijke groet,\nSign Company`,
    datum: daysAgo(1, 16, 0),
    gelezen: true,
    starred: false,
    labels: ['offerte'],
    bijlagen: 0,
    map: 'concepten',
    created_at: daysAgo(1, 16, 0),
  },

  // ── GEPLAND ──
  {
    id: 'email-030',
    user_id: 'demo-user',
    gmail_id: 'gm-030',
    van: 'Sign Company <studio@signcompany.nl>',
    aan: 'pieter@bakkerijvandijk.nl',
    onderwerp: 'Herinnering: offerte lichtreclame verloopt binnenkort',
    inhoud: `Beste Pieter,\n\nGraag herinner ik je eraan dat onze offerte OFR-2026-018 voor de lichtreclame over 5 dagen verloopt.\n\nMocht je nog vragen hebben of willen bespreken, neem gerust contact op. We kijken ernaar uit om dit project voor jullie te realiseren!\n\nMet vriendelijke groet,\nSign Company`,
    datum: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    gelezen: true,
    starred: false,
    labels: ['offerte'],
    bijlagen: 0,
    map: 'gepland',
    scheduled_at: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: daysAgo(0, 8, 0),
  },
]

// ── Demo projecten (sign-company specific) ──

const demoProjecten: Project[] = [
  {
    id: 'proj-001',
    user_id: 'demo-user',
    klant_id: 'klant-001',
    klant_naam: 'Bakkerij Van Dijk',
    naam: 'Lichtreclame gevel Bakkerij Van Dijk',
    beschrijving: 'Doosletters met LED verlichting op de gevel. Aluminium 3mm, wit gepoedercoat, 3500x600mm. Inclusief montage en aansluiting.',
    status: 'actief',
    prioriteit: 'hoog',
    start_datum: daysAgo(14).split('T')[0],
    eind_datum: new Date(Date.now() + 21 * 86400000).toISOString().split('T')[0],
    budget: 3850,
    besteed: 1200,
    voortgang: 40,
    team_leden: [],
    created_at: daysAgo(14),
    updated_at: daysAgo(1),
  },
  {
    id: 'proj-002',
    user_id: 'demo-user',
    klant_id: 'klant-002',
    klant_naam: 'Garage Jansen',
    naam: 'Complete signing nieuw pand Garage Jansen',
    beschrijving: 'Gevelreclame, reclamezuil, interne signing en autobelettering. Nieuw bedrijfspand Industrieweg 44 Zoetermeer.',
    status: 'gepland',
    prioriteit: 'medium',
    start_datum: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    eind_datum: new Date(Date.now() + 60 * 86400000).toISOString().split('T')[0],
    budget: 12500,
    besteed: 0,
    voortgang: 0,
    team_leden: [],
    created_at: daysAgo(7),
    updated_at: daysAgo(2),
  },
  {
    id: 'proj-003',
    user_id: 'demo-user',
    klant_id: 'klant-003',
    klant_naam: 'Restaurant De Gouden Leeuw',
    naam: 'Terrassigning De Gouden Leeuw',
    beschrijving: 'Menuboards buiten (dibond wisselframe), windschermen met logo (mesh), uithandbord dubbelzijdig met LED.',
    status: 'actief',
    prioriteit: 'medium',
    start_datum: daysAgo(5).split('T')[0],
    eind_datum: new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0],
    budget: 4200,
    besteed: 800,
    voortgang: 20,
    team_leden: [],
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },
]

// ── Demo offertes ──

const demoOffertes: Offerte[] = [
  {
    id: 'off-001',
    user_id: 'demo-user',
    klant_id: 'klant-001',
    klant_naam: 'Bakkerij Van Dijk',
    project_id: 'proj-001',
    nummer: 'OFR-2026-018',
    titel: 'Lichtreclame doosletters gevel',
    status: 'goedgekeurd',
    notities: 'LED doosletters op aluminium gevel, inclusief montage',
    totaal: 3850,
    subtotaal: 3181.82,
    btw_bedrag: 668.18,
    geldig_tot: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
    voorwaarden: '',
    created_at: daysAgo(14),
    updated_at: daysAgo(7),
  },
  {
    id: 'off-002',
    user_id: 'demo-user',
    klant_id: 'klant-002',
    klant_naam: 'Garage Jansen',
    project_id: 'proj-002',
    nummer: 'OFR-2026-021',
    titel: 'Gevelreclame + reclamezuil nieuw pand',
    status: 'verzonden',
    notities: 'Doosletters gevel, reclamezuil ingang, interne wayfinding',
    totaal: 12500,
    subtotaal: 10330.58,
    btw_bedrag: 2169.42,
    geldig_tot: new Date(Date.now() + 20 * 86400000).toISOString().split('T')[0],
    voorwaarden: '',
    created_at: daysAgo(7),
    updated_at: daysAgo(2),
  },
  {
    id: 'off-003',
    user_id: 'demo-user',
    klant_id: 'klant-003',
    klant_naam: 'Restaurant De Gouden Leeuw',
    project_id: 'proj-003',
    nummer: 'OFR-2026-022',
    titel: 'Terrassigning compleet',
    status: 'gefactureerd',
    notities: 'Menuboards, windschermen, uithandbord',
    totaal: 4200,
    subtotaal: 3471.07,
    btw_bedrag: 728.93,
    geldig_tot: new Date(Date.now() + 12 * 86400000).toISOString().split('T')[0],
    voorwaarden: '',
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },
  {
    id: 'off-004',
    user_id: 'demo-user',
    klant_id: 'klant-004',
    klant_naam: 'Advocatenkantoor Visser & Partners',
    nummer: 'OFR-2026-023',
    titel: 'RVS geveletters Herengracht',
    status: 'concept',
    notities: 'Geborsteld RVS letters op monumentale gevel, inclusief vergunningsaanvraag',
    totaal: 5800,
    subtotaal: 4793.39,
    btw_bedrag: 1006.61,
    geldig_tot: new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0],
    voorwaarden: '',
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
  },
]

// ── Demo offerte items ──

const demoOfferteItems: OfferteItem[] = [
  {
    id: 'oi-001', user_id: 'demo-user', offerte_id: 'off-001',
    beschrijving: 'Doosletters "Bakkerij Van Dijk" - LED verlicht',
    aantal: 1, eenheidsprijs: 2800, btw_percentage: 21, korting_percentage: 0,
    totaal: 2800, volgorde: 1,
    created_at: daysAgo(14),
  },
  {
    id: 'oi-002', user_id: 'demo-user', offerte_id: 'off-001',
    beschrijving: 'Montage en elektrische aansluiting',
    aantal: 1, eenheidsprijs: 650, btw_percentage: 21, korting_percentage: 0,
    totaal: 650, volgorde: 2,
    created_at: daysAgo(14),
  },
  {
    id: 'oi-003', user_id: 'demo-user', offerte_id: 'off-001',
    beschrijving: 'Raambelettering openingstijden (2 ramen)',
    aantal: 2, eenheidsprijs: 200, btw_percentage: 21, korting_percentage: 0,
    totaal: 400, volgorde: 3,
    created_at: daysAgo(14),
  },
]

// ── Demo taken ──

const demoTaken: Taak[] = [
  {
    id: 'taak-001', user_id: 'demo-user', project_id: 'proj-001',
    titel: 'Ontwerp doosletters finaliseren',
    beschrijving: 'Kleur, lettertype en afmetingen definitief maken',
    status: 'bezig', prioriteit: 'hoog',
    toegewezen_aan: '', geschatte_tijd: 4, bestede_tijd: 2,
    deadline: new Date().toISOString().split('T')[0],
    created_at: daysAgo(7), updated_at: daysAgo(1),
  },
  {
    id: 'taak-002', user_id: 'demo-user', project_id: 'proj-001',
    titel: 'LED modules bestellen bij leverancier',
    beschrijving: 'Samsung LED modules 6500K, 12V, IP65 waterdicht',
    status: 'todo', prioriteit: 'medium',
    toegewezen_aan: '', geschatte_tijd: 1, bestede_tijd: 0,
    deadline: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    created_at: daysAgo(5), updated_at: daysAgo(2),
  },
  {
    id: 'taak-003', user_id: 'demo-user', project_id: 'proj-001',
    titel: 'Aluminium platen laten CNC frezen',
    beschrijving: '3mm aluminium, wit gepoedercoat, letters uitfrezen',
    status: 'todo', prioriteit: 'medium',
    toegewezen_aan: '', geschatte_tijd: 2, bestede_tijd: 0,
    deadline: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
    created_at: daysAgo(3), updated_at: daysAgo(1),
  },
  {
    id: 'taak-004', user_id: 'demo-user', project_id: 'proj-002',
    titel: 'Opname nieuw pand Garage Jansen',
    beschrijving: 'Opmeten gevel, locatie zuil, interne routing',
    status: 'todo', prioriteit: 'hoog',
    toegewezen_aan: '', geschatte_tijd: 3, bestede_tijd: 0,
    deadline: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
    created_at: daysAgo(2), updated_at: daysAgo(1),
  },
  {
    id: 'taak-005', user_id: 'demo-user', project_id: 'proj-003',
    titel: 'Windscherm designs naar drukker sturen',
    beschrijving: 'Full color print op mesh doek, 4 stuks met logo',
    status: 'todo', prioriteit: 'laag',
    toegewezen_aan: '', geschatte_tijd: 1, bestede_tijd: 0,
    deadline: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    created_at: daysAgo(3), updated_at: daysAgo(1),
  },
]

// ── Demo montage afspraken ──

const demoMontageAfspraken: MontageAfspraak[] = [
  {
    id: 'mont-001',
    user_id: 'demo-user',
    klant_id: 'klant-001',
    klant_naam: 'Bakkerij Van Dijk',
    project_id: 'proj-001',
    titel: 'Montage doosletters Bakkerij Van Dijk',
    beschrijving: 'Plaatsing LED doosletters op gevel. Hoogwerker nodig.',
    datum: new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
    start_tijd: '08:00',
    eind_tijd: '12:00',
    locatie: 'Broodstraat 12, Rotterdam',
    status: 'gepland',
    monteurs: ['Jan', 'Kees'],
    materialen: ['Doosletters set', 'Bevestigingsmateriaal', 'LED driver'],
    notities: 'Hoogwerker nodig. Parkeervergunning aangevraagd.',
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
  },
  {
    id: 'mont-002',
    user_id: 'demo-user',
    klant_id: 'klant-001',
    klant_naam: 'Bakkerij Van Dijk',
    project_id: 'proj-001',
    titel: 'Raambelettering Bakkerij Van Dijk',
    beschrijving: 'Aanbrengen vinyl raambelettering, 2 ramen',
    datum: new Date(Date.now() + 15 * 86400000).toISOString().split('T')[0],
    start_tijd: '09:00',
    eind_tijd: '11:00',
    locatie: 'Broodstraat 12, Rotterdam',
    status: 'gepland',
    monteurs: ['Kees'],
    materialen: ['Vinyl folie', 'Applicatievloeistof', 'Rakel'],
    notities: 'Ramen moeten schoon en droog zijn.',
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
  },
]

// ── Demo facturen ──

const demoFacturen: Factuur[] = [
  {
    id: 'fact-001',
    user_id: 'demo-user',
    klant_id: 'klant-001',
    klant_naam: 'Bakkerij Van Dijk',
    offerte_id: 'off-001',
    project_id: 'proj-001',
    nummer: 'FAC-2026-012',
    titel: 'Raambelettering openingstijden (2 ramen)',
    status: 'betaald',
    subtotaal: 400,
    btw_bedrag: 84,
    totaal: 484,
    betaald_bedrag: 484,
    factuurdatum: daysAgo(21).split('T')[0],
    vervaldatum: daysAgo(7).split('T')[0],
    betaaldatum: daysAgo(10).split('T')[0],
    notities: 'Deelbetaling raambelettering, snel voldaan.',
    voorwaarden: 'Betaling binnen 14 dagen na factuurdatum.',
    bron_type: 'offerte',
    bron_offerte_id: 'off-001',
    bron_project_id: 'proj-001',
    betaaltermijn_dagen: 14,
    factuur_type: 'standaard',
    created_at: daysAgo(21),
    updated_at: daysAgo(10),
  },
  {
    id: 'fact-002',
    user_id: 'demo-user',
    klant_id: 'klant-003',
    klant_naam: 'Restaurant De Gouden Leeuw',
    offerte_id: 'off-003',
    project_id: 'proj-003',
    nummer: 'FAC-2026-013',
    titel: 'Voorschotfactuur terrassigning',
    status: 'verzonden',
    subtotaal: 1735.54,
    btw_bedrag: 364.46,
    totaal: 2100,
    betaald_bedrag: 0,
    factuurdatum: daysAgo(5).split('T')[0],
    vervaldatum: new Date(Date.now() + 9 * 86400000).toISOString().split('T')[0],
    notities: '50% voorschot terrassigning conform offerte OFR-2026-022.',
    voorwaarden: 'Betaling binnen 14 dagen na factuurdatum.',
    bron_type: 'offerte',
    bron_offerte_id: 'off-003',
    bron_project_id: 'proj-003',
    betaaltermijn_dagen: 14,
    factuur_type: 'voorschot',
    voorschot_percentage: 50,
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
  },
  {
    id: 'fact-003',
    user_id: 'demo-user',
    klant_id: 'klant-005',
    klant_naam: 'PrintWorks BV',
    nummer: 'FAC-2026-010',
    titel: 'Vinyl belettering 3 bedrijfswagens',
    status: 'vervallen',
    subtotaal: 1860,
    btw_bedrag: 390.60,
    totaal: 2250.60,
    betaald_bedrag: 0,
    factuurdatum: daysAgo(45).split('T')[0],
    vervaldatum: daysAgo(15).split('T')[0],
    betalingsherinnering_verzonden: true,
    notities: 'Full-wrap belettering 3x Volkswagen Transporter.',
    voorwaarden: 'Betaling binnen 30 dagen na factuurdatum.',
    bron_type: 'handmatig',
    betaaltermijn_dagen: 30,
    herinnering_1_verstuurd: daysAgo(14),
    factuur_type: 'standaard',
    created_at: daysAgo(45),
    updated_at: daysAgo(14),
  },
]

const demoFactuurItems: FactuurItem[] = [
  {
    id: 'fi-001',
    user_id: 'demo-user',
    factuur_id: 'fact-001',
    beschrijving: 'Raambelettering openingstijden',
    aantal: 2,
    eenheidsprijs: 200,
    btw_percentage: 21,
    korting_percentage: 0,
    totaal: 400,
    volgorde: 1,
    created_at: daysAgo(21),
  },
  {
    id: 'fi-002',
    user_id: 'demo-user',
    factuur_id: 'fact-002',
    beschrijving: 'Menuboards buiten - Dibond wisselframe (2 stuks)',
    aantal: 2,
    eenheidsprijs: 450,
    btw_percentage: 21,
    korting_percentage: 0,
    totaal: 900,
    volgorde: 1,
    created_at: daysAgo(5),
  },
  {
    id: 'fi-003',
    user_id: 'demo-user',
    factuur_id: 'fact-002',
    beschrijving: 'Windschermen met logo - mesh doek (4 stuks) - 50% voorschot',
    aantal: 2,
    eenheidsprijs: 300,
    btw_percentage: 21,
    korting_percentage: 0,
    totaal: 600,
    volgorde: 2,
    created_at: daysAgo(5),
  },
  {
    id: 'fi-004',
    user_id: 'demo-user',
    factuur_id: 'fact-002',
    beschrijving: 'Uithandbord dubbelzijdig LED - 50% voorschot',
    aantal: 1,
    eenheidsprijs: 235.54,
    btw_percentage: 21,
    korting_percentage: 0,
    totaal: 235.54,
    volgorde: 3,
    created_at: daysAgo(5),
  },
  {
    id: 'fi-005',
    user_id: 'demo-user',
    factuur_id: 'fact-003',
    beschrijving: 'Full-wrap belettering Volkswagen Transporter',
    aantal: 3,
    eenheidsprijs: 620,
    btw_percentage: 21,
    korting_percentage: 0,
    totaal: 1860,
    volgorde: 1,
    created_at: daysAgo(45),
  },
]

// ── Initialization ──

export function useDataInit() {
  const [isReady, setIsReady] = useState(false)

  useEffect(() => {
    try {
      // Ensure all localStorage keys exist as empty arrays if not present
      for (const key of storageKeys) {
        if (!localStorage.getItem(key)) {
          safeSetItem(key, '[]')
        }
      }

      // Seed demo data if empty (first-time users get example content)
      const seedIfEmpty = (key: string, data: unknown[]) => {
        const existing = JSON.parse(localStorage.getItem(key) || '[]')
        if (existing.length === 0) {
          safeSetItem(key, JSON.stringify(data))
        }
      }

      seedIfEmpty('forgedesk_emails', demoEmails)
      seedIfEmpty('forgedesk_klanten', demoKlanten)
      seedIfEmpty('forgedesk_projecten', demoProjecten)
      seedIfEmpty('forgedesk_offertes', demoOffertes)
      seedIfEmpty('forgedesk_offerte_items', demoOfferteItems)
      seedIfEmpty('forgedesk_taken', demoTaken)
      seedIfEmpty('forgedesk_montage_afspraken', demoMontageAfspraken)
      seedIfEmpty('forgedesk_facturen', demoFacturen)
      seedIfEmpty('forgedesk_factuur_items', demoFactuurItems)

      // Seed demo credits voor visualizer
      const creditsKey = 'forgedesk_visualizer_credits_demo-user'
      if (!localStorage.getItem(creditsKey)) {
        safeSetItem(creditsKey, JSON.stringify({
          user_id: 'demo-user',
          saldo: 25,
          totaal_gekocht: 25,
          totaal_gebruikt: 0,
          laatst_bijgewerkt: new Date().toISOString(),
        }))
      }
    } catch (e) {
      console.warn('localStorage init failed:', e)
    }

    setIsReady(true)
  }, [])

  return { isReady }
}
