-- NIET AUTOMATISCH UITVOEREN
ALTER TABLE public.ai_chats DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.emails DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificaties DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.portaal_bestanden DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.portaal_reacties DISABLE ROW LEVEL SECURITY;
