import React, { createContext, useContext, useState, useEffect, ReactNode, useCallback } from 'react'

type Language = 'nl' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, Record<string, string>>> = {
  nl: {
    // Navigation
    nav: {
      dashboard: 'Dashboard',
      projecten: 'Projecten',
      klanten: 'Klanten',
      taken: 'Taken',
      offertes: 'Offertes',
      documenten: 'Documenten',
      email: 'E-mail',
      agenda: 'Agenda',
      boekhouding: 'Boekhouding',
      ai_assistent: 'AI Assistent',
      instellingen: 'Instellingen',
      profiel: 'Profiel',
      help: 'Help & Ondersteuning',
    },

    // Common / Shared
    common: {
      opslaan: 'Opslaan',
      annuleren: 'Annuleren',
      verwijderen: 'Verwijderen',
      bewerken: 'Bewerken',
      toevoegen: 'Toevoegen',
      zoeken: 'Zoeken...',
      filteren: 'Filteren',
      sorteren: 'Sorteren',
      exporteren: 'Exporteren',
      importeren: 'Importeren',
      downloaden: 'Downloaden',
      uploaden: 'Uploaden',
      sluiten: 'Sluiten',
      bevestigen: 'Bevestigen',
      terug: 'Terug',
      volgende: 'Volgende',
      vorige: 'Vorige',
      laden: 'Laden...',
      geen_resultaten: 'Geen resultaten gevonden',
      weet_je_zeker: 'Weet je het zeker?',
      ja: 'Ja',
      nee: 'Nee',
      of: 'of',
      en: 'en',
      alle: 'Alle',
      meer_laden: 'Meer laden',
      acties: 'Acties',
      details: 'Details',
      overzicht: 'Overzicht',
      nieuw: 'Nieuw',
      kopieren: 'Kopiëren',
      gekopieerd: 'Gekopieerd!',
      selecteer: 'Selecteer',
      geen: 'Geen',
      onbekend: 'Onbekend',
      verplicht_veld: 'Dit veld is verplicht',
      ongeldige_email: 'Ongeldig e-mailadres',
      opgeslagen: 'Succesvol opgeslagen',
      verwijderd: 'Succesvol verwijderd',
      fout_opgetreden: 'Er is een fout opgetreden',
      probeer_opnieuw: 'Probeer opnieuw',
      items_per_pagina: 'Items per pagina',
      van: 'van',
      tot: 'tot',
      resultaten: 'resultaten',
    },

    // Status labels
    status: {
      actief: 'Actief',
      inactief: 'Inactief',
      prospect: 'Prospect',
      gepland: 'Gepland',
      'in-review': 'In Review',
      afgerond: 'Afgerond',
      'on-hold': 'On Hold',
      concept: 'Concept',
      verzonden: 'Verzonden',
      bekeken: 'Bekeken',
      goedgekeurd: 'Goedgekeurd',
      afgewezen: 'Afgewezen',
      todo: 'Te Doen',
      bezig: 'Bezig',
      review: 'Review',
      klaar: 'Klaar',
      definitief: 'Definitief',
      gearchiveerd: 'Gearchiveerd',
    },

    // Priority labels
    prioriteit: {
      laag: 'Laag',
      medium: 'Medium',
      hoog: 'Hoog',
      kritiek: 'Kritiek',
    },

    // Dashboard
    dashboard: {
      welkom: 'Welkom terug',
      actieve_projecten: 'Actieve Projecten',
      openstaande_taken: 'Openstaande Taken',
      totale_omzet: 'Totale Omzet',
      ongelezen_emails: 'Ongelezen E-mails',
      recente_activiteit: 'Recente Activiteit',
      komende_deadlines: 'Komende Deadlines',
      snelle_acties: 'Snelle Acties',
      nieuw_project: 'Nieuw Project',
      nieuwe_offerte: 'Nieuwe Offerte',
      nieuwe_klant: 'Nieuwe Klant',
      nieuwe_taak: 'Nieuwe Taak',
      deze_week: 'Deze Week',
      deze_maand: 'Deze Maand',
      dit_jaar: 'Dit Jaar',
      omzet_overzicht: 'Omzet Overzicht',
      project_voortgang: 'Project Voortgang',
      geen_recente_activiteit: 'Geen recente activiteit',
    },

    // Klanten (Clients)
    klanten: {
      titel: 'Klanten',
      nieuwe_klant: 'Nieuwe Klant',
      klant_toevoegen: 'Klant Toevoegen',
      klant_bewerken: 'Klant Bewerken',
      klant_verwijderen: 'Klant Verwijderen',
      bedrijfsnaam: 'Bedrijfsnaam',
      contactpersoon: 'Contactpersoon',
      email: 'E-mail',
      telefoon: 'Telefoon',
      adres: 'Adres',
      postcode: 'Postcode',
      stad: 'Stad',
      land: 'Land',
      website: 'Website',
      kvk_nummer: 'KvK Nummer',
      btw_nummer: 'BTW Nummer',
      status: 'Status',
      tags: 'Tags',
      notities: 'Notities',
      aantal_projecten: 'Projecten',
      totale_waarde: 'Totale Waarde',
      laatste_contact: 'Laatste Contact',
      klant_details: 'Klantdetails',
      contactgegevens: 'Contactgegevens',
      bedrijfsgegevens: 'Bedrijfsgegevens',
      geen_klanten: 'Geen klanten gevonden',
      klant_aangemaakt: 'Klant succesvol aangemaakt',
      klant_bijgewerkt: 'Klant succesvol bijgewerkt',
      klant_verwijderd: 'Klant succesvol verwijderd',
      verwijder_bevestiging: 'Weet je zeker dat je deze klant wilt verwijderen?',
    },

    // Projecten (Projects)
    projecten: {
      titel: 'Projecten',
      nieuw_project: 'Nieuw Project',
      project_toevoegen: 'Project Toevoegen',
      project_bewerken: 'Project Bewerken',
      project_verwijderen: 'Project Verwijderen',
      naam: 'Projectnaam',
      beschrijving: 'Beschrijving',
      klant: 'Klant',
      status: 'Status',
      prioriteit: 'Prioriteit',
      start_datum: 'Startdatum',
      eind_datum: 'Einddatum',
      budget: 'Budget',
      besteed: 'Besteed',
      voortgang: 'Voortgang',
      team_leden: 'Teamleden',
      taken: 'Taken',
      documenten: 'Documenten',
      project_details: 'Projectdetails',
      geen_projecten: 'Geen projecten gevonden',
      project_aangemaakt: 'Project succesvol aangemaakt',
      project_bijgewerkt: 'Project succesvol bijgewerkt',
      project_verwijderd: 'Project succesvol verwijderd',
      verwijder_bevestiging: 'Weet je zeker dat je dit project wilt verwijderen?',
      overschreden_budget: 'Budget overschreden',
      op_schema: 'Op schema',
      vertraagd: 'Vertraagd',
    },

    // Taken (Tasks)
    taken: {
      titel: 'Taken',
      nieuwe_taak: 'Nieuwe Taak',
      taak_toevoegen: 'Taak Toevoegen',
      taak_bewerken: 'Taak Bewerken',
      taak_verwijderen: 'Taak Verwijderen',
      taak_titel: 'Titel',
      beschrijving: 'Beschrijving',
      project: 'Project',
      status: 'Status',
      prioriteit: 'Prioriteit',
      toegewezen_aan: 'Toegewezen Aan',
      deadline: 'Deadline',
      geschatte_tijd: 'Geschatte Tijd',
      bestede_tijd: 'Bestede Tijd',
      uren: 'uur',
      taak_details: 'Taakdetails',
      geen_taken: 'Geen taken gevonden',
      taak_aangemaakt: 'Taak succesvol aangemaakt',
      taak_bijgewerkt: 'Taak succesvol bijgewerkt',
      taak_verwijderd: 'Taak succesvol verwijderd',
      verwijder_bevestiging: 'Weet je zeker dat je deze taak wilt verwijderen?',
      sleep_om_te_ordenen: 'Sleep om te ordenen',
      kanban_weergave: 'Kanban Weergave',
      lijst_weergave: 'Lijst Weergave',
    },

    // Offertes (Quotes)
    offertes: {
      titel: 'Offertes',
      nieuwe_offerte: 'Nieuwe Offerte',
      offerte_toevoegen: 'Offerte Toevoegen',
      offerte_bewerken: 'Offerte Bewerken',
      offerte_verwijderen: 'Offerte Verwijderen',
      nummer: 'Offertenummer',
      offerte_titel: 'Titel',
      klant: 'Klant',
      status: 'Status',
      subtotaal: 'Subtotaal',
      btw_bedrag: 'BTW Bedrag',
      totaal: 'Totaal',
      geldig_tot: 'Geldig Tot',
      notities: 'Notities',
      voorwaarden: 'Voorwaarden',
      regels: 'Offerteregels',
      regel_toevoegen: 'Regel Toevoegen',
      beschrijving: 'Beschrijving',
      aantal: 'Aantal',
      eenheidsprijs: 'Eenheidsprijs',
      btw_percentage: 'BTW %',
      korting_percentage: 'Korting %',
      regel_totaal: 'Totaal',
      offerte_details: 'Offertedetails',
      geen_offertes: 'Geen offertes gevonden',
      offerte_aangemaakt: 'Offerte succesvol aangemaakt',
      offerte_bijgewerkt: 'Offerte succesvol bijgewerkt',
      offerte_verwijderd: 'Offerte succesvol verwijderd',
      verwijder_bevestiging: 'Weet je zeker dat je deze offerte wilt verwijderen?',
      verstuur: 'Offerte Versturen',
      pdf_downloaden: 'PDF Downloaden',
      dupliceren: 'Dupliceren',
      verlopen: 'Verlopen',
    },

    // Documenten (Documents)
    documenten: {
      titel: 'Documenten',
      nieuw_document: 'Nieuw Document',
      uploaden: 'Document Uploaden',
      naam: 'Naam',
      type: 'Type',
      grootte: 'Grootte',
      map: 'Map',
      status: 'Status',
      tags: 'Tags',
      gedeeld_met: 'Gedeeld Met',
      project: 'Project',
      klant: 'Klant',
      geen_documenten: 'Geen documenten gevonden',
      document_geupload: 'Document succesvol geüpload',
      document_verwijderd: 'Document succesvol verwijderd',
      verwijder_bevestiging: 'Weet je zeker dat je dit document wilt verwijderen?',
      sleep_bestanden: 'Sleep bestanden hierheen of klik om te uploaden',
      max_grootte: 'Maximale bestandsgrootte',
      ondersteunde_formaten: 'Ondersteunde formaten',
      downloaden: 'Downloaden',
      delen: 'Delen',
      verplaatsen: 'Verplaatsen',
      nieuwe_map: 'Nieuwe Map',
    },

    // E-mail
    email: {
      titel: 'E-mail',
      nieuw_bericht: 'Nieuw Bericht',
      inbox: 'Inbox',
      verzonden: 'Verzonden',
      concepten: 'Concepten',
      prullenbak: 'Prullenbak',
      van: 'Van',
      aan: 'Aan',
      onderwerp: 'Onderwerp',
      datum: 'Datum',
      bijlagen: 'Bijlagen',
      beantwoorden: 'Beantwoorden',
      allen_beantwoorden: 'Allen Beantwoorden',
      doorsturen: 'Doorsturen',
      markeer_gelezen: 'Markeer als Gelezen',
      markeer_ongelezen: 'Markeer als Ongelezen',
      archiveren: 'Archiveren',
      geen_emails: 'Geen e-mails gevonden',
      bericht_verzonden: 'Bericht succesvol verzonden',
      labels: 'Labels',
      ster: 'Ster',
      zoek_emails: 'Zoeken in e-mails...',
    },

    // Agenda (Calendar)
    agenda: {
      titel: 'Agenda',
      nieuw_evenement: 'Nieuw Evenement',
      evenement_toevoegen: 'Evenement Toevoegen',
      evenement_bewerken: 'Evenement Bewerken',
      evenement_verwijderen: 'Evenement Verwijderen',
      evenement_titel: 'Titel',
      beschrijving: 'Beschrijving',
      start_datum: 'Startdatum',
      eind_datum: 'Einddatum',
      type: 'Type',
      locatie: 'Locatie',
      deelnemers: 'Deelnemers',
      kleur: 'Kleur',
      herhaling: 'Herhaling',
      meeting: 'Vergadering',
      deadline: 'Deadline',
      herinnering: 'Herinnering',
      persoonlijk: 'Persoonlijk',
      dag_weergave: 'Dag',
      week_weergave: 'Week',
      maand_weergave: 'Maand',
      vandaag: 'Vandaag',
      geen_evenementen: 'Geen evenementen',
      evenement_aangemaakt: 'Evenement succesvol aangemaakt',
      evenement_bijgewerkt: 'Evenement succesvol bijgewerkt',
      evenement_verwijderd: 'Evenement succesvol verwijderd',
      verwijder_bevestiging: 'Weet je zeker dat je dit evenement wilt verwijderen?',
      geen_herhaling: 'Geen herhaling',
      dagelijks: 'Dagelijks',
      wekelijks: 'Wekelijks',
      maandelijks: 'Maandelijks',
      jaarlijks: 'Jaarlijks',
    },

    // Boekhouding (Accounting)
    boekhouding: {
      titel: 'Boekhouding',
      grootboek: 'Grootboek',
      btw_codes: 'BTW Codes',
      kortingen: 'Kortingen',
      code: 'Code',
      naam: 'Naam',
      categorie: 'Categorie',
      saldo: 'Saldo',
      activa: 'Activa',
      passiva: 'Passiva',
      omzet: 'Omzet',
      kosten: 'Kosten',
      omschrijving: 'Omschrijving',
      percentage: 'Percentage',
      type: 'Type',
      waarde: 'Waarde',
      voorwaarden: 'Voorwaarden',
      percentage_korting: 'Percentage',
      vast_bedrag: 'Vast Bedrag',
      nieuw_grootboek: 'Nieuw Grootboekrekening',
      nieuwe_btw_code: 'Nieuwe BTW Code',
      nieuwe_korting: 'Nieuwe Korting',
      geen_grootboek: 'Geen grootboekrekeningen gevonden',
      geen_btw_codes: 'Geen BTW codes gevonden',
      geen_kortingen: 'Geen kortingen gevonden',
      totaal_activa: 'Totaal Activa',
      totaal_passiva: 'Totaal Passiva',
      totaal_omzet: 'Totaal Omzet',
      totaal_kosten: 'Totaal Kosten',
    },

    // AI Assistent
    ai: {
      titel: 'AI Assistent',
      placeholder: 'Stel een vraag...',
      versturen: 'Versturen',
      nieuw_gesprek: 'Nieuw Gesprek',
      geschiedenis: 'Geschiedenis',
      suggesties: 'Suggesties',
      denkt_na: 'AI denkt na...',
      fout: 'Er ging iets mis. Probeer opnieuw.',
      welkom_bericht: 'Hallo! Ik ben je AI assistent. Hoe kan ik je helpen?',
    },

    // Instellingen (Settings)
    instellingen: {
      titel: 'Instellingen',
      profiel: 'Profiel',
      account: 'Account',
      voornaam: 'Voornaam',
      achternaam: 'Achternaam',
      email: 'E-mail',
      telefoon: 'Telefoon',
      bedrijfsnaam: 'Bedrijfsnaam',
      bedrijfs_adres: 'Bedrijfsadres',
      kvk_nummer: 'KvK Nummer',
      btw_nummer: 'BTW Nummer',
      taal: 'Taal',
      theme: 'Thema',
      licht: 'Licht',
      donker: 'Donker',
      nederlands: 'Nederlands',
      engels: 'Engels',
      avatar: 'Profielfoto',
      avatar_wijzigen: 'Profielfoto Wijzigen',
      wachtwoord_wijzigen: 'Wachtwoord Wijzigen',
      huidig_wachtwoord: 'Huidig Wachtwoord',
      nieuw_wachtwoord: 'Nieuw Wachtwoord',
      bevestig_wachtwoord: 'Bevestig Wachtwoord',
      profiel_bijgewerkt: 'Profiel succesvol bijgewerkt',
      wachtwoord_bijgewerkt: 'Wachtwoord succesvol bijgewerkt',
      notificaties: 'Notificaties',
      email_notificaties: 'E-mail Notificaties',
      push_notificaties: 'Push Notificaties',
    },

    // Auth
    auth: {
      inloggen: 'Inloggen',
      registreren: 'Registreren',
      uitloggen: 'Uitloggen',
      email: 'E-mailadres',
      wachtwoord: 'Wachtwoord',
      wachtwoord_vergeten: 'Wachtwoord Vergeten?',
      geen_account: 'Nog geen account?',
      al_account: 'Al een account?',
      welkom: 'Welkom bij Sign Company',
      inlog_subtitle: 'Log in om verder te gaan',
      register_subtitle: 'Maak een nieuw account aan',
      voornaam: 'Voornaam',
      achternaam: 'Achternaam',
      ongeldig_email: 'Ongeldig e-mailadres',
      wachtwoord_kort: 'Wachtwoord moet minimaal 6 tekens zijn',
      inloggen_mislukt: 'Inloggen mislukt. Controleer je gegevens.',
      registreren_mislukt: 'Registreren mislukt. Probeer opnieuw.',
    },

    // Tijdseenheden en datums
    tijd: {
      seconde: 'seconde',
      seconden: 'seconden',
      minuut: 'minuut',
      minuten: 'minuten',
      uur: 'uur',
      uren: 'uren',
      dag: 'dag',
      dagen: 'dagen',
      week: 'week',
      weken: 'weken',
      maand: 'maand',
      maanden: 'maanden',
      jaar: 'jaar',
      jaren: 'jaren',
      geleden: 'geleden',
      over: 'over',
    },
  },

  en: {
    // Navigation
    nav: {
      dashboard: 'Dashboard',
      projecten: 'Projects',
      klanten: 'Clients',
      taken: 'Tasks',
      offertes: 'Quotes',
      documenten: 'Documents',
      email: 'Email',
      agenda: 'Calendar',
      boekhouding: 'Accounting',
      ai_assistent: 'AI Assistant',
      instellingen: 'Settings',
      profiel: 'Profile',
      help: 'Help & Support',
    },

    // Common / Shared
    common: {
      opslaan: 'Save',
      annuleren: 'Cancel',
      verwijderen: 'Delete',
      bewerken: 'Edit',
      toevoegen: 'Add',
      zoeken: 'Search...',
      filteren: 'Filter',
      sorteren: 'Sort',
      exporteren: 'Export',
      importeren: 'Import',
      downloaden: 'Download',
      uploaden: 'Upload',
      sluiten: 'Close',
      bevestigen: 'Confirm',
      terug: 'Back',
      volgende: 'Next',
      vorige: 'Previous',
      laden: 'Loading...',
      geen_resultaten: 'No results found',
      weet_je_zeker: 'Are you sure?',
      ja: 'Yes',
      nee: 'No',
      of: 'or',
      en: 'and',
      alle: 'All',
      meer_laden: 'Load more',
      acties: 'Actions',
      details: 'Details',
      overzicht: 'Overview',
      nieuw: 'New',
      kopieren: 'Copy',
      gekopieerd: 'Copied!',
      selecteer: 'Select',
      geen: 'None',
      onbekend: 'Unknown',
      verplicht_veld: 'This field is required',
      ongeldige_email: 'Invalid email address',
      opgeslagen: 'Saved successfully',
      verwijderd: 'Deleted successfully',
      fout_opgetreden: 'An error occurred',
      probeer_opnieuw: 'Try again',
      items_per_pagina: 'Items per page',
      van: 'from',
      tot: 'to',
      resultaten: 'results',
    },

    // Status labels
    status: {
      actief: 'Active',
      inactief: 'Inactive',
      prospect: 'Prospect',
      gepland: 'Planned',
      'in-review': 'In Review',
      afgerond: 'Completed',
      'on-hold': 'On Hold',
      concept: 'Draft',
      verzonden: 'Sent',
      bekeken: 'Viewed',
      goedgekeurd: 'Approved',
      afgewezen: 'Rejected',
      todo: 'To Do',
      bezig: 'In Progress',
      review: 'Review',
      klaar: 'Done',
      definitief: 'Final',
      gearchiveerd: 'Archived',
    },

    // Priority labels
    prioriteit: {
      laag: 'Low',
      medium: 'Medium',
      hoog: 'High',
      kritiek: 'Critical',
    },

    // Dashboard
    dashboard: {
      welkom: 'Welcome back',
      actieve_projecten: 'Active Projects',
      openstaande_taken: 'Open Tasks',
      totale_omzet: 'Total Revenue',
      ongelezen_emails: 'Unread Emails',
      recente_activiteit: 'Recent Activity',
      komende_deadlines: 'Upcoming Deadlines',
      snelle_acties: 'Quick Actions',
      nieuw_project: 'New Project',
      nieuwe_offerte: 'New Quote',
      nieuwe_klant: 'New Client',
      nieuwe_taak: 'New Task',
      deze_week: 'This Week',
      deze_maand: 'This Month',
      dit_jaar: 'This Year',
      omzet_overzicht: 'Revenue Overview',
      project_voortgang: 'Project Progress',
      geen_recente_activiteit: 'No recent activity',
    },

    // Klanten (Clients)
    klanten: {
      titel: 'Clients',
      nieuwe_klant: 'New Client',
      klant_toevoegen: 'Add Client',
      klant_bewerken: 'Edit Client',
      klant_verwijderen: 'Delete Client',
      bedrijfsnaam: 'Company Name',
      contactpersoon: 'Contact Person',
      email: 'Email',
      telefoon: 'Phone',
      adres: 'Address',
      postcode: 'Postal Code',
      stad: 'City',
      land: 'Country',
      website: 'Website',
      kvk_nummer: 'Chamber of Commerce No.',
      btw_nummer: 'VAT Number',
      status: 'Status',
      tags: 'Tags',
      notities: 'Notes',
      aantal_projecten: 'Projects',
      totale_waarde: 'Total Value',
      laatste_contact: 'Last Contact',
      klant_details: 'Client Details',
      contactgegevens: 'Contact Details',
      bedrijfsgegevens: 'Company Details',
      geen_klanten: 'No clients found',
      klant_aangemaakt: 'Client created successfully',
      klant_bijgewerkt: 'Client updated successfully',
      klant_verwijderd: 'Client deleted successfully',
      verwijder_bevestiging: 'Are you sure you want to delete this client?',
    },

    // Projecten (Projects)
    projecten: {
      titel: 'Projects',
      nieuw_project: 'New Project',
      project_toevoegen: 'Add Project',
      project_bewerken: 'Edit Project',
      project_verwijderen: 'Delete Project',
      naam: 'Project Name',
      beschrijving: 'Description',
      klant: 'Client',
      status: 'Status',
      prioriteit: 'Priority',
      start_datum: 'Start Date',
      eind_datum: 'End Date',
      budget: 'Budget',
      besteed: 'Spent',
      voortgang: 'Progress',
      team_leden: 'Team Members',
      taken: 'Tasks',
      documenten: 'Documents',
      project_details: 'Project Details',
      geen_projecten: 'No projects found',
      project_aangemaakt: 'Project created successfully',
      project_bijgewerkt: 'Project updated successfully',
      project_verwijderd: 'Project deleted successfully',
      verwijder_bevestiging: 'Are you sure you want to delete this project?',
      overschreden_budget: 'Budget exceeded',
      op_schema: 'On schedule',
      vertraagd: 'Delayed',
    },

    // Taken (Tasks)
    taken: {
      titel: 'Tasks',
      nieuwe_taak: 'New Task',
      taak_toevoegen: 'Add Task',
      taak_bewerken: 'Edit Task',
      taak_verwijderen: 'Delete Task',
      taak_titel: 'Title',
      beschrijving: 'Description',
      project: 'Project',
      status: 'Status',
      prioriteit: 'Priority',
      toegewezen_aan: 'Assigned To',
      deadline: 'Deadline',
      geschatte_tijd: 'Estimated Time',
      bestede_tijd: 'Time Spent',
      uren: 'hours',
      taak_details: 'Task Details',
      geen_taken: 'No tasks found',
      taak_aangemaakt: 'Task created successfully',
      taak_bijgewerkt: 'Task updated successfully',
      taak_verwijderd: 'Task deleted successfully',
      verwijder_bevestiging: 'Are you sure you want to delete this task?',
      sleep_om_te_ordenen: 'Drag to reorder',
      kanban_weergave: 'Kanban View',
      lijst_weergave: 'List View',
    },

    // Offertes (Quotes)
    offertes: {
      titel: 'Quotes',
      nieuwe_offerte: 'New Quote',
      offerte_toevoegen: 'Add Quote',
      offerte_bewerken: 'Edit Quote',
      offerte_verwijderen: 'Delete Quote',
      nummer: 'Quote Number',
      offerte_titel: 'Title',
      klant: 'Client',
      status: 'Status',
      subtotaal: 'Subtotal',
      btw_bedrag: 'VAT Amount',
      totaal: 'Total',
      geldig_tot: 'Valid Until',
      notities: 'Notes',
      voorwaarden: 'Terms & Conditions',
      regels: 'Quote Lines',
      regel_toevoegen: 'Add Line',
      beschrijving: 'Description',
      aantal: 'Quantity',
      eenheidsprijs: 'Unit Price',
      btw_percentage: 'VAT %',
      korting_percentage: 'Discount %',
      regel_totaal: 'Total',
      offerte_details: 'Quote Details',
      geen_offertes: 'No quotes found',
      offerte_aangemaakt: 'Quote created successfully',
      offerte_bijgewerkt: 'Quote updated successfully',
      offerte_verwijderd: 'Quote deleted successfully',
      verwijder_bevestiging: 'Are you sure you want to delete this quote?',
      verstuur: 'Send Quote',
      pdf_downloaden: 'Download PDF',
      dupliceren: 'Duplicate',
      verlopen: 'Expired',
    },

    // Documenten (Documents)
    documenten: {
      titel: 'Documents',
      nieuw_document: 'New Document',
      uploaden: 'Upload Document',
      naam: 'Name',
      type: 'Type',
      grootte: 'Size',
      map: 'Folder',
      status: 'Status',
      tags: 'Tags',
      gedeeld_met: 'Shared With',
      project: 'Project',
      klant: 'Client',
      geen_documenten: 'No documents found',
      document_geupload: 'Document uploaded successfully',
      document_verwijderd: 'Document deleted successfully',
      verwijder_bevestiging: 'Are you sure you want to delete this document?',
      sleep_bestanden: 'Drag files here or click to upload',
      max_grootte: 'Maximum file size',
      ondersteunde_formaten: 'Supported formats',
      downloaden: 'Download',
      delen: 'Share',
      verplaatsen: 'Move',
      nieuwe_map: 'New Folder',
    },

    // E-mail
    email: {
      titel: 'Email',
      nieuw_bericht: 'New Message',
      inbox: 'Inbox',
      verzonden: 'Sent',
      concepten: 'Drafts',
      prullenbak: 'Trash',
      van: 'From',
      aan: 'To',
      onderwerp: 'Subject',
      datum: 'Date',
      bijlagen: 'Attachments',
      beantwoorden: 'Reply',
      allen_beantwoorden: 'Reply All',
      doorsturen: 'Forward',
      markeer_gelezen: 'Mark as Read',
      markeer_ongelezen: 'Mark as Unread',
      archiveren: 'Archive',
      geen_emails: 'No emails found',
      bericht_verzonden: 'Message sent successfully',
      labels: 'Labels',
      ster: 'Star',
      zoek_emails: 'Search emails...',
    },

    // Agenda (Calendar)
    agenda: {
      titel: 'Calendar',
      nieuw_evenement: 'New Event',
      evenement_toevoegen: 'Add Event',
      evenement_bewerken: 'Edit Event',
      evenement_verwijderen: 'Delete Event',
      evenement_titel: 'Title',
      beschrijving: 'Description',
      start_datum: 'Start Date',
      eind_datum: 'End Date',
      type: 'Type',
      locatie: 'Location',
      deelnemers: 'Participants',
      kleur: 'Color',
      herhaling: 'Recurrence',
      meeting: 'Meeting',
      deadline: 'Deadline',
      herinnering: 'Reminder',
      persoonlijk: 'Personal',
      dag_weergave: 'Day',
      week_weergave: 'Week',
      maand_weergave: 'Month',
      vandaag: 'Today',
      geen_evenementen: 'No events',
      evenement_aangemaakt: 'Event created successfully',
      evenement_bijgewerkt: 'Event updated successfully',
      evenement_verwijderd: 'Event deleted successfully',
      verwijder_bevestiging: 'Are you sure you want to delete this event?',
      geen_herhaling: 'No recurrence',
      dagelijks: 'Daily',
      wekelijks: 'Weekly',
      maandelijks: 'Monthly',
      jaarlijks: 'Yearly',
    },

    // Boekhouding (Accounting)
    boekhouding: {
      titel: 'Accounting',
      grootboek: 'General Ledger',
      btw_codes: 'VAT Codes',
      kortingen: 'Discounts',
      code: 'Code',
      naam: 'Name',
      categorie: 'Category',
      saldo: 'Balance',
      activa: 'Assets',
      passiva: 'Liabilities',
      omzet: 'Revenue',
      kosten: 'Expenses',
      omschrijving: 'Description',
      percentage: 'Percentage',
      type: 'Type',
      waarde: 'Value',
      voorwaarden: 'Conditions',
      percentage_korting: 'Percentage',
      vast_bedrag: 'Fixed Amount',
      nieuw_grootboek: 'New Ledger Account',
      nieuwe_btw_code: 'New VAT Code',
      nieuwe_korting: 'New Discount',
      geen_grootboek: 'No ledger accounts found',
      geen_btw_codes: 'No VAT codes found',
      geen_kortingen: 'No discounts found',
      totaal_activa: 'Total Assets',
      totaal_passiva: 'Total Liabilities',
      totaal_omzet: 'Total Revenue',
      totaal_kosten: 'Total Expenses',
    },

    // AI Assistent
    ai: {
      titel: 'AI Assistant',
      placeholder: 'Ask a question...',
      versturen: 'Send',
      nieuw_gesprek: 'New Conversation',
      geschiedenis: 'History',
      suggesties: 'Suggestions',
      denkt_na: 'AI is thinking...',
      fout: 'Something went wrong. Please try again.',
      welkom_bericht: 'Hello! I am your AI assistant. How can I help you?',
    },

    // Instellingen (Settings)
    instellingen: {
      titel: 'Settings',
      profiel: 'Profile',
      account: 'Account',
      voornaam: 'First Name',
      achternaam: 'Last Name',
      email: 'Email',
      telefoon: 'Phone',
      bedrijfsnaam: 'Company Name',
      bedrijfs_adres: 'Company Address',
      kvk_nummer: 'Chamber of Commerce No.',
      btw_nummer: 'VAT Number',
      taal: 'Language',
      theme: 'Theme',
      licht: 'Light',
      donker: 'Dark',
      nederlands: 'Dutch',
      engels: 'English',
      avatar: 'Profile Photo',
      avatar_wijzigen: 'Change Profile Photo',
      wachtwoord_wijzigen: 'Change Password',
      huidig_wachtwoord: 'Current Password',
      nieuw_wachtwoord: 'New Password',
      bevestig_wachtwoord: 'Confirm Password',
      profiel_bijgewerkt: 'Profile updated successfully',
      wachtwoord_bijgewerkt: 'Password updated successfully',
      notificaties: 'Notifications',
      email_notificaties: 'Email Notifications',
      push_notificaties: 'Push Notifications',
    },

    // Auth
    auth: {
      inloggen: 'Sign In',
      registreren: 'Sign Up',
      uitloggen: 'Sign Out',
      email: 'Email Address',
      wachtwoord: 'Password',
      wachtwoord_vergeten: 'Forgot Password?',
      geen_account: "Don't have an account?",
      al_account: 'Already have an account?',
      welkom: 'Welcome to Sign Company',
      inlog_subtitle: 'Sign in to continue',
      register_subtitle: 'Create a new account',
      voornaam: 'First Name',
      achternaam: 'Last Name',
      ongeldig_email: 'Invalid email address',
      wachtwoord_kort: 'Password must be at least 6 characters',
      inloggen_mislukt: 'Sign in failed. Please check your credentials.',
      registreren_mislukt: 'Sign up failed. Please try again.',
    },

    // Tijdseenheden en datums
    tijd: {
      seconde: 'second',
      seconden: 'seconds',
      minuut: 'minute',
      minuten: 'minutes',
      uur: 'hour',
      uren: 'hours',
      dag: 'day',
      dagen: 'days',
      week: 'week',
      weken: 'weeks',
      maand: 'month',
      maanden: 'months',
      jaar: 'year',
      jaren: 'years',
      geleden: 'ago',
      over: 'in',
    },
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('doen_language')
    return stored === 'en' ? 'en' : 'nl'
  })

  useEffect(() => {
    localStorage.setItem('doen_language', language)
    document.documentElement.lang = language
  }, [language])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
  }

  const t = useCallback((key: string): string => {
    const parts = key.split('.')
    if (parts.length !== 2) return key

    const [section, field] = parts
    const langTranslations = translations[language]

    if (langTranslations && langTranslations[section] && langTranslations[section][field]) {
      return langTranslations[section][field]
    }

    // Fallback to Dutch if key not found in current language
    if (language !== 'nl' && translations.nl[section] && translations.nl[section][field]) {
      return translations.nl[section][field]
    }

    return key
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
