-- 029: Trial en onboarding kolommen
-- DRAAI DIT HANDMATIG in de Supabase SQL Editor

ALTER TABLE organisaties
  ADD COLUMN IF NOT EXISTS trial_start TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS trial_einde TIMESTAMPTZ DEFAULT NOW() + INTERVAL '30 days',
  ADD COLUMN IF NOT EXISTS is_betaald BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT,
  ADD COLUMN IF NOT EXISTS stripe_subscription_id TEXT,
  ADD COLUMN IF NOT EXISTS abonnement_status TEXT DEFAULT 'trial',
  ADD COLUMN IF NOT EXISTS onboarding_compleet BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS onboarding_stap INTEGER DEFAULT 0;

ALTER TABLE klanten ADD COLUMN IF NOT EXISTS is_demo_data BOOLEAN DEFAULT FALSE;
ALTER TABLE projecten ADD COLUMN IF NOT EXISTS is_demo_data BOOLEAN DEFAULT FALSE;
ALTER TABLE offertes ADD COLUMN IF NOT EXISTS is_demo_data BOOLEAN DEFAULT FALSE;
ALTER TABLE taken ADD COLUMN IF NOT EXISTS is_demo_data BOOLEAN DEFAULT FALSE;
